language: python
os:
    - linux
env:
    - INSTALL_EXTRA=0
    - INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
addons:
    apt_packages:
        - gfortran
        - gcc
before_install:
    - pip install -r requirements.txt
    - bash requirements.extra $INSTALL_EXTRA
install:
    - "python setup.py install"
script:
    - "coverage run --source=ocbpy setup.py test"
after_success: coveralls
allow_failures:
   - python: "3.5"
     env: INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
   - python: "3.6"
     env: INSTALL_EXTRA=2 CDF_LIB=$HOME/lib