language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false

install:
    - source activate test-environment
    - pip install coveralls
    - "python setup.py install"

# Command to run tests not sorted yet
#script:
#    - unittests --with-coverage --cover-package=ocbpy
after_success:
    coveralls
