language: python
python:
    - "2.7"
sudo: false

install:
    - source activate test-environment
    - pip install coveralls
    - "python setup.py install"
script:
    - unittests --with-coverage --cover-package=ocbpy
after_success:
    coveralls