language: python
os:
    - linux
env:
    - INSTALL_EXTRA=0
    - INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
jobs:
   allow_failures:
      - env: INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
addons:
    apt_packages:
        - gfortran
        - gcc
install:
    - pip install tox-travis
script:
    - TOXENV=$TOXENV-$INSTALL_EXTRA
    - echo "TEST: " $TOXENV
    - tox