language: python
os:
    - linux
env:
    global:
        - CDF_LIB=$HOME/lib
    jobs:
        - INSTALL_EXTRA=0
        - INSTALL_EXTRA=2
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
jobs:
    allow_failures:
        - env: INSTALL_EXTRA=2
    include:
        - stage: coveralls
          script: tox -e cover
cache:
    directories:
        - $HOME/cover
addons:
    apt_packages:
        - gfortran
        - gcc
install:
    - pip install tox-travis
script:
    - tox -e $(echo py$TRAVIS_PYTHON_VERSION-extra$INSTALL_EXTRA | tr -d .)