language: python
os:
    - linux

env:
    global:
        - CDF_LIB=$HOME/lib
        - COVERALLS_PARALLEL=true
    jobs:
        - INSTALL_EXTRA=0
        - INSTALL_EXTRA=1
        - INSTALL_EXTRA=2
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8

jobs:
   allow_failures:
      - env: INSTALL_EXTRA=1
      - env: INSTALL_EXTRA=2
addons:
    apt_packages:
        - gfortran
        - gcc

before_install:
    - pip install -rrequirements.txt coveralls
    - bash requirements.extra $INSTALL_EXTRA

install:
    - python setup.py install

script:
    - coverage run --rcfile=.coveragerc -m unittest discover

after_success:
    - coveralls --rcfile=.coveragerc

notifications:
  webhooks: https://coveralls.io/webhook
