language: python
os:
    - linux
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
install:
    - source activate test-environment
    - pip install coveralls
    - "python setup.py install"
script:
    - "coverage run --source=ocbpy setup.py test"
after_success: coveralls
