language: python
jobs:
    include:
    - name: "Mac: Python 2.7 with SSJ_Auroral_Boundary"
      os: osx
      python: "2.7"
      env: INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
    - name: "Linux: Python 2.7 with SSJ_Auroral_Boundary"
      os: linux
      python: "2.7"
      env: INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
    - name: "Python 3.5 basic install"
      os: osx
      python: "3.5"
      env: INSTALL_EXTRA=0
    - name: "Python 3.5 basic install"
      os: linux
      python: "3.5"
      env: INSTALL_EXTRA=0
    - name: "Python 3.6 basic install"
      os: osx
      python: "3.6"
      env: INSTALL_EXTRA=0
    - name: "Python 3.6 basic install"
      os: linux
      python: "3.6"
      env: INSTALL_EXTRA=0
    - name: "Python 3.7 basic install"
      os: osx
      python: "3.7"
      env: INSTALL_EXTRA=0
    - name: "Python 3.7 basic install"
      os: linux
      python: "3.7"
      env: INSTALL_EXTRA=0
addons:
    apt_packages:
        - gfortran
        - gcc
before_install:
    - pip install -r requirements.txt
    - bash requirements.extra $INSTALL_EXTRA
install:
    - "python setup.py install"
script:
    - "coverage run --source=ocbpy setup.py test"
after_success: coveralls
