language: python
os:
    - linux

env:
    global:
        - CDF_LIB=$HOME/lib
        - COVERALLS_PARALLEL=true
    jobs:
        - INSTALL_EXTRA=0
        - INSTALL_EXTRA=1
        - INSTALL_EXTRA=2
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

jobs:
   allow_failures:
      - env: INSTALL_EXTRA=1
      - env: INSTALL_EXTRA=2
addons:
    apt_packages:
        - gfortran
        - gcc

before_install:
    - pip install -rrequirements.txt coveralls flake8
    - bash requirements.extra $INSTALL_EXTRA

install:
    - python setup.py install

script:
    - if [[ $INSTALL_EXTRA == 0 ]]; then flake8 ocbpy; fi
    - coverage run --rcfile=.coveragerc -m unittest discover

after_success:
    - coveralls --rcfile=.coveragerc

notifications:
  webhooks: https://coveralls.io/webhook
