#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags
skip_tags: true

# Masimum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

init:
  - ps: echo $env:TESTENV

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

before_test:
  - cmd: type c:\projects\ocbpy\ocbpy\tests\test_data\out_vort

test_script:
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

build: off
configuration: Release

install:
  - '%PYTHON%\\python.exe -m pip install logbook wheel numpy setuptools'

#deploy_script:
  # if tagged commit, build/upload wheel
#  - python setup.py bdist_wheel
#  - IF "%TESTENV%"=="2.7-nocover-64" (
#      python setup.py sdist
#    )
#  - IF "%APPVEYOR_REPO_TAG%"=="true" IF NOT "%TESTENV%"=="check" (
#      pip install twine &&
#      twine upload -u %PYPI_USER% -p %PYPI_PASS% dist/*
#    )

artifacts:
  - path: dist/*

#matrix:
#  allow_failures:
#    - PYTHON_VERSION: '3.5'

