# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: unittest with flake8

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        install-extras: ["base", "pysat_instruments", "dmsp_ssj"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} with ${{ matrix.install-extras }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install standard and test dependencies
      run: pip install .[test]

    - name: Install extra dependencies
      if: ${{ !startsWith(matrix.install-extras, 'base') }}
      run: pip install .[${{ matrix.install-extras }}]

    - name: Set up pysat
      if: startsWith(matrix.install-extras, 'pysat')
      run: |
        mkdir pysatData
        python -c "import pysat; pysat.params['data_dirs'] = 'pysatData'"

    - name: Install AACGMV2 RC
      run: |
        pip install --no-deps -i https://test.pypi.org/simple/ aacgmv2==2.7.1rc1
        python -c "import aacgmv2; print(aacgmv2.__version__)"

    - name: Test PEP8 compliance
      run: flake8 . --count --show-source --statistics

    - name: Evaluate complexity
      run: flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Run unit and integration tests
      run: |
        coverage run --rcfile=pyproject.toml -m unittest discover
        coverage report
        coverage xml --rcfile=pyproject.toml

    - name:  Coveralls Parallel
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run=${{ join(matrix.*, '-') }}
        parallel: true
        format: cobertura
        debug: true

  finish:
    name: Finish Coverage Analysis
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Coveralls Finished
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true
        run: |
          curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz
          ./coveralls done --build-number ${{ github.run_number }}
