# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: unittest with flake8

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
	include:
	- python-version: ["3.8", "3.9"]
	  os: windows-latest
	

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install standard and test dependencies, then ocbpy
      run: |
        python -m pip install --upgrade pip
        pip install -rrequirements.txt coveralls flake8
        bash requirements.extra 0
        python setup.py install

    - name: Windows installs
      if: matrix.os == 'windows-latest'
      run: pip install setuptools coverage

    - name: Test PEP8 compliance
      if: matrix.os == 'ubuntu-latest'
      run: flake8 . --count --show-source --statistics

    - name: Evaluate complexity
      if: matrix.os == 'ubuntu-latest'
      run: flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Run unit and integration tests
      run: coverage run --rcfile=setup.cfg -m unittest discover

    - name: Publish results to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
