# This workflow will install Python dependencies, run tests on Windows with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: Windows unittest with flake8

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install standard and test dependencies, then ocbpy
      run: |
        pip install -r requirements.txt
        bash requirements.extra 0
        python setup.py install

    - name: Run unit and integration tests
      run: coverage run --rcfile=setup.cfg -m unittest discover

    - name: Publish results to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
